if loaded_lua_globals_file then return end
local loaded_lua_globals_file = true
loadfile("crawl-rc/lua/config.lua")

GLOBALS = {}
GLOBALS.EMOJI = {}

if CONFIG.emojis then
  GLOBALS.EMOJI.RARE_ITEM = "💎"
  GLOBALS.EMOJI.ORB = "🔮"
  GLOBALS.EMOJI.TALISMAN = "🧬"
  GLOBALS.EMOJI.BODY_ARMOUR = "🛡️"
  GLOBALS.EMOJI.ARMOUR = "🛡️"

  GLOBALS.EMOJI.WEAPON = "⚔️"
  GLOBALS.EMOJI.RANGED = "🏹"
  GLOBALS.EMOJI.POLEARM = "🔱"
  GLOBALS.EMOJI.TWO_HANDED = "✋🤚"
  GLOBALS.EMOJI.HAT = "🧢"
  GLOBALS.EMOJI.GLOVES = "🧤"
  GLOBALS.EMOJI.BOOTS = "🥾"
  GLOBALS.EMOJI.STAFF_RESISTANCE = "🏳️‍🌈"

  GLOBALS.EMOJI.ACCURACY = "🎯"
  GLOBALS.EMOJI.STRONGER = "💪"
  GLOBALS.EMOJI.STRONGEST = "💪💪"
  GLOBALS.EMOJI.EGO = "🧪"
  GLOBALS.EMOJI.LIGHTER = "⏬"
  GLOBALS.EMOJI.HEAVIER = "⏫"
  GLOBALS.EMOJI.ARTEFACT = "💠"

  GLOBALS.EMOJI.REMIND_IDENTIFY = "🎁"
  GLOBALS.EMOJI.EXCLAMATION = "‼️"

  GLOBALS.EMOJI.HP_100 = "❤️❤️❤️❤️❤️"
  GLOBALS.EMOJI.HP_90  = "❤️❤️❤️❤️❤️‍🩹"
  GLOBALS.EMOJI.HP_80  = "❤️❤️❤️❤️🤍"
  GLOBALS.EMOJI.HP_70  = "❤️❤️❤️❤️‍🩹🤍"
  GLOBALS.EMOJI.HP_60  = "❤️❤️❤️🤍🤍"
  GLOBALS.EMOJI.HP_50  = "❤️❤️❤️‍🩹🤍🤍"
  GLOBALS.EMOJI.HP_40  = "❤️❤️🤍🤍🤍"
  GLOBALS.EMOJI.HP_30  = "❤️❤️‍🩹🤍🤍🤍"
  GLOBALS.EMOJI.HP_20  = "❤️🤍🤍🤍🤍"
  GLOBALS.EMOJI.HP_10  = "❤️‍🩹🤍🤍🤍🤍"
  GLOBALS.EMOJI.HP_0   = "🤍🤍🤍🤍🤍"

else
  -- Text fallbacks
  GLOBALS.EMOJI.REMIND_IDENTIFY = with_color("cyan", "??")
  GLOBALS.EMOJI.EXCLAMATION = with_color("lightred", "!!")

  local BORDER = with_color("white", "|")
  local FULL_PIP = with_color("lightred", "+")
  local PART_PIP = with_color("lightgrey", "+")
  local EMPTY_PIP = with_color("darkgrey", "-")
  GLOBALS.EMOJI.HP_100 = BORDER .. FULL_PIP .. FULL_PIP .. FULL_PIP .. FULL_PIP .. FULL_PIP .. BORDER
  GLOBALS.EMOJI.HP_90  = BORDER .. FULL_PIP .. FULL_PIP .. FULL_PIP .. FULL_PIP .. PART_PIP .. BORDER
  GLOBALS.EMOJI.HP_80  = BORDER .. FULL_PIP .. FULL_PIP .. FULL_PIP .. PART_PIP .. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_70  = BORDER .. FULL_PIP .. FULL_PIP .. FULL_PIP .. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_60  = BORDER .. FULL_PIP .. FULL_PIP .. PART_PIP .. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_50  = BORDER .. FULL_PIP .. FULL_PIP .. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_40  = BORDER .. FULL_PIP .. PART_PIP .. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_30  = BORDER .. FULL_PIP .. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_20  = BORDER .. FULL_PIP .. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_10  = BORDER .. PART_PIP .. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. BORDER
  GLOBALS.EMOJI.HP_0   = BORDER .. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. EMPTY_PIP.. BORDER

end
